print("Guess the number")
print("I am thinking of a 3-digit number. Try to guess what it is")
print("\nGame instructions:")
print("RightWrong means One digit is correct but in the wrong position")
print("RightRight means One digit is correct and in the right position")
print("WrongWrong means No digit is correct")
